apiVersion: v1
kind: Pod
metadata:
  name: my-nginx
  labels:
    component: web
    name: my-ngnix
spec:
  containers:
  - name: my-nginx
    image: nginx:alpine
    ports:
      - containerPort: 80
