apiVersion: v1
kind: Pod
metadata:
  name: my-nginx-pod
  labels:
    component: web
    name: my-app
spec:
  containers:
  - name: my-nginx
    image: mpiatk/changednginx
    ports:
      - containerPort: 80
